language: cpp

compiler:
  - gcc

script:
  - sudo docker ps -a
  - sudo docker run --name cpp-bridge-v5 -v $(pwd):/root/cpp-bridge-v5 amidukr/cpp-bridge-v5 /root/cpp-bridge-v5/scripts/run-ci-docker.sh

