language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - sudo apt install -y --show-progress cmake libgtest-dev libgl1-mesa-dev libglfw3-dev libglew-dev libeigen3-dev libopencv-dev

script: cmake .. && cmake --build .

